#!/usr/bin/env bash
# Claude Code status line — generated by statusline-setup agent

input=$(cat)

cwd=$(echo "$input" | jq -r '.workspace.current_dir // .cwd // empty')
model=$(echo "$input" | jq -r '.model.display_name // empty')
used=$(echo "$input" | jq -r '.context_window.used_percentage // empty')
remaining=$(echo "$input" | jq -r '.context_window.remaining_percentage // empty')

input_tokens=$(echo "$input" | jq -r '.context_window.total_input_tokens // empty')
output_tokens=$(echo "$input" | jq -r '.context_window.total_output_tokens // empty')
exceeds_200k_tokens=$(echo "$input" | jq -r '.exceeds_200k_tokens // empty')


# Abbreviate path: ~/../../project-dir
shorten_path() {
  local dir="${1:-$(pwd)}"
  local home="$HOME"
  if [[ "$dir" == "$home" ]]; then
    echo "~"
    return
  fi
  if [[ "$dir" == "$home"/* ]]; then
    local rel="${dir#$home/}"
    local depth=$(echo "$rel" | tr '/' '\n' | wc -l)
    local base=$(basename "$dir")
    if [ "$depth" -le 2 ]; then
      echo "~/$rel"
    else
      echo "~/…/$base"
    fi
  else
    local depth=$(echo "$dir" | tr '/' '\n' | wc -l)
    local base=$(basename "$dir")
    if [ "$depth" -le 3 ]; then
      echo "$dir"
    else
      echo "/…/$base"
    fi
  fi
}

short_cwd=$(shorten_path "${cwd:-$(pwd)}")

# Build user@host:dir segment (matches PS1 style)
user_host_dir=$(printf "\033[01;32m%s@%s\033[00m:\033[01;34m%s\033[00m" "$(whoami)" "$(hostname -s)" "$short_cwd")

# Build context segment
ctx_segment=""
if [ -n "$used" ] && [ "$used" != "null" ]; then
  used_int=$(printf "%.0f" "$used")
  remaining_int=$(printf "%.0f" "${remaining:-0}")
  ctx_segment=" | ctx: ${used_int}% used / ${remaining_int}% left"
fi

# Build tokens segment
tokens_segment=""
if [ -n "$input_tokens" ] && [ "$input_tokens" != "null" ] && [ -n "$output_tokens" ] && [ "$output_tokens" != "null" ]; then
  in_k=$(awk "BEGIN {printf \"%.1f\", $input_tokens/1000}")
  out_k=$(awk "BEGIN {printf \"%.1f\", $output_tokens/1000}")
  tokens_segment=" | tokens: in ${in_k}k / out ${out_k}k"
  if [ "$exceeds_200k_tokens" = "true" ]; then
    tokens_segment="${tokens_segment} (>200k)"
  fi
fi

# Build model segment
model_segment=""
if [ -n "$model" ] && [ "$model" != "null" ]; then
  model_segment=" | ${model}"
fi

# Rate limits (Claude.ai subscribers only)
rate_segment=""
five=$(echo "$input" | jq -r '.rate_limits.five_hour.used_percentage // empty')
week=$(echo "$input" | jq -r '.rate_limits.seven_day.used_percentage // empty')
if [ -n "$five" ] && [ "$five" != "null" ]; then
  rate_segment=" | 5h:$(printf '%.0f' "$five")%"
fi
if [ -n "$week" ] && [ "$week" != "null" ]; then
  rate_segment="${rate_segment} 7d:$(printf '%.0f' "$week")%"
fi

printf "%b%s%s%s%s\n" "$user_host_dir" "$ctx_segment" "$tokens_segment" "$model_segment" "$rate_segment"
